### ISSUE TITLE
error on first build: Could not get unknown property 'MYAPP_RELEASE_STORE_FILE

### ISSUE THREAD

**Issue by WillyRamirez** [junedomingo/movieapp#12]
Hi all,

When trying to run this app I get the following error (on windows 7 running android) 

> Could not get unknown property 'MYAPP_RELEASE_STORE_FILE' for SigningConfig_De
corated{name=release, storeFile=null, storePassword=null, keyAlias=null, keyPass
word=null, storeType=null, v1SigningEnabled=true, v2SigningEnabled=true} of type
 com.android.build.gradle.internal.dsl.SigningConfig.

App runs after removing below lines from build.gradle
`  storeFile file(MYAPP_RELEASE_STORE_FILE)
   storePassword MYAPP_RELEASE_STORE_PASSWORD
   keyAlias MYAPP_RELEASE_KEY_ALIAS
   keyPassword MYAPP_RELEASE_KEY_PASSWORD`

However, when running the app I get the following 
![image](https://cloud.githubusercontent.com/assets/8708591/24247781/580b9a00-0fcd-11e7-89ae-6ce1777c3baa.png)

Anyone else running on windows or know how to solve this? Thnx

**Comment by WillyRamirez** [comment]
Ok, turns out the .env file had a filename in Windows. Renamed it via notepad (all filetypes). Error is gone

**Comment by WillyRamirez** [comment]
Sorry, everyone for the confusion, my error is not gone, I even redid the entire installation. Still get the gradle build error, and also the above one

**Comment by junedomingo** [comment]
Hi @WillyRamirez , in android/app/build.gradle, can you try deleting  line 100-107 and line 120.

**Comment by WillyRamirez** [comment]
Hi and thanks for the fast reply @junedomingo , I applied your fix.
the "MYAPP_RELEASE_STORE_FILE" error is gone, but the "cant find variable: process" error above is still present

Error doesn't occur on my Mac (although there it doesn't work either, different issue)
