### ISSUE TITLE
How do you register the application?

### ISSUE THREAD

**Issue by pmlarocque** [junedomingo/movieapp#22]
Hello,

Thanks for the work and example, kind of trying to replicate this with RNN v2, but I cannot make my repository to work.

I cannot find where you call 
`AppRegistry.registerComponent("movieapp", () => ...)`
or equivalent anywhere.
So my version get the 

> Application [name] has not been registered. error

Could you please elaborate ? I did a few hypothesis, but none worked.

Thanks!

**Comment by Gskflute** [comment]
I want to know this too please.

No idea how to run the app without AppRegistry

**Comment by pmlarocque** [comment]
Look like Navigation.registerContainer does call appregistry but there is no container named  movieapp, so I still don’t know.

**Comment by Gskflute** [comment]
Where did he call Navigation.registerContainer?? i only found Navigation.registerComponent inside the registerScreens main function

**Comment by pmlarocque** [comment]
Sorry I might be mixing up function names, and working with v2 personally and function have been renamed. And on my phone right now cannot check. I’ll keep you updated when I make progress.

**Comment by pmlarocque** [comment]
@Gskflute haven't found it yet 😞

**Comment by pmlarocque** [comment]
@Gskflute  I'll confirm soon but I think I got it, you have to edit AppDelegate.m. I'll slap myself for not reading the documentation well enough.

See point 5 here: https://wix.github.io/react-native-navigation/#/installation-ios

**Comment by pmlarocque** [comment]
@Gskflute made it work, I was right, it is really the AppDelegate.m see my repo: https://github.com/pmlarocque/fuckingWix

It is with RNN V2.
