### ISSUE TITLE
I got issues when tried to build your app.

### ISSUE THREAD

**Issue by anhchuyen** [junedomingo/movieapp#3]
The issues was in app.js file, this line:
export const TMDB_URL = Config.TMDB_URL;

I can't find the .env file that will be read from react-native-config. It returned an error: "null is not an object (evaluating '_reactnativeConfig2.default.TMDB_URL')
-----------
Please help...

**Comment by junedomingo** [comment]
@anhchuyen I think you forgot to create `.env` file in your root directory. https://github.com/JuneDomingo/movieapp#installation

**Comment by anhchuyen** [comment]
Thank you, I just noticed that I forgot to read the instruction..Now the app is running, thanks your for works...
