### ISSUE TITLE
Unable to build under Windows 10 / MacOS

### ISSUE THREAD

**Issue by tstkenny** [junedomingo/movieapp#4]
Hi,  I tried to build this project in both platforms but no luck.

npm install returns quite some dependencies error like whatwg-fetch is now required by jest which leads to needing react 15.4.1, etc.

After fixing all those errors, react-native run-android returns error:
:app:generateDebugBuildConfig FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDebugBuildConfig'.
> Failed to create C:\rn\movieapp\android\app\build\generated\source\buildConfig\debug\com\movieapp

I am doing this under windows cmd, administrator mode already.

Really want to try this project out.  Kindly help if you can spare some.  Thank you!

**Comment by junedomingo** [comment]
make sure you installed required SDK platforms. 
try `android --clean-cache` and run again
