### ISSUE TITLE
undefined const on constants/api.js

### ISSUE THREAD

**Issue by arhysaid** [junedomingo/movieapp#5]
Hy june..

i have tried to run this source for learning, but i got some problem on react-native-config
on constants/api.js all line got error undefined, i see in react-native-config documentation it need .env on root directory, like 

API_URL=https://myapi.com
GOOGLE_MAPS_API_KEY=abcdefgh

but i don't see it in your source
Thanks for helping btw..

**Comment by junedomingo** [comment]
Hey @arhysaid, Right. you need to create `.env` file for `react-native-config` as I also mention in the [docs](https://github.com/JuneDomingo/movieapp#installation) :-)
