### ISSUE TITLE
com.facebook.react.common.javascriptexception{}

### ISSUE THREAD

**Issue by adylimmo** [junedomingo/movieapp#6]
![screenshot_2017-01-15-00-30-47](https://cloud.githubusercontent.com/assets/22222644/21956749/0de0bac0-daba-11e6-94cd-769ae69c1f6f.png)

how to fix it.. thanks.

**Comment by junedomingo** [comment]
Hi @adylimmo , i'm not really sure what's going on in here. Could you send me what are your dev environment versions?

**Comment by adylimmo** [comment]
hi @JuneDomingo ,

im use 
OS windows 10 

by step :
- git clone https://github.com/JuneDomingo/movieapp.git
- cd movieapp
- make file .env in folder movieapp
- npm install --save
- react-native run-android (installed in android 5.1.1)
first error
![screenshot_2017-01-15-22-52-49](https://cloud.githubusercontent.com/assets/22222644/21963964/83b85e22-db75-11e6-93b0-e3de2d08e890.png)


- shake and im select debug

and then show error com.facebook.react.common.javascriptexception{} ,
how to fix.

thanks.

**Comment by yildirimburak** [comment]
Sorry i do not know anything

2017-01-15 18:32 GMT+03:00 adylimmo <notifications@github.com>:

**Comment by junedomingo** [comment]
@adylimmo , can you try just running `npm install` or install YARN  in your machine and run `yarn install`.

Make sure you also include the API_VARIABLES etc. into your `.env` file.

**Comment by adylimmo** [comment]
thanks @JuneDomingo is work..

i'm solved "yarn install"
